apiVersion: v1
kind: Service
metadata:
  name: iperf-server-service
spec:
  selector:
    app: iperf
    role: server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
---
apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-server-job
spec:
  template:
    metadata:
      labels:
        app: iperf
        role: server
    spec:
      containers:
      - name: iperf-server
        image: networkstatic/iperf3
        command: ["/bin/sh", "-c"]
        args:
          - >
            iperf3 -s;
            sleep 3600
        ports:
        - containerPort: 5201
        resources:
          limits:
            cpu: "5"
            memory: "4Gi"
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-job
spec:
  template:
    metadata:
      labels:
        app: iperf
        role: client
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: iperf
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: iperf-client
        image: networkstatic/iperf3
        command: ["/bin/sh", "-c"]
        args:
          - >
            sleep 10; 
            iperf3 -c iperf-server-service -P 8 -t 30;
            sleep 3600
        resources:
          limits:
            cpu: "5"
            memory: "4Gi"
      restartPolicy: Never


