# tfjob-nfs-dataset-storage-volume.yaml
# To store SQuAD v1.1 dataset for BERT finetuning
# dataset 저장용 PV/PVC
# Lambda Labs 이전하면서, nfs -> hostpath 로 변경.
# Hostpath를 공유 스토리지로 두면 에러 남 -> 각각의 로컬 스토리지로 변경함. 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfjob-nfs-dataset-storage
  labels:
    type: local
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/tensorspot/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfjob-nfs-dataset-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 900Gi
  storageClassName: manual
