apiVersion: v1
kind: ServiceAccount
metadata:
  name: tensorspot-scheduler
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tensorspot-scheduler
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["tensorspot.ku"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tensorspot-scheduler
subjects:
- kind: ServiceAccount
  name: tensorspot-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: tensorspot-scheduler
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: tensorspot-scheduler
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    app: tensorspot-scheduler
spec:
  serviceAccountName: tensorspot-scheduler
  priorityClassName: system-node-critical
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  #jhlee
  - key: "node-role.kubernetes.io/master"
  #- key: "node-role.kubernetes.io"
    #value: "master"
    #operator: "Equal"
    operator: "Exists"
    #effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
  restartPolicy: Never
  containers:
  - name: tensorspot-scheduler
    image: chiefmate/tensorspot_ps:v10.2-k8sbinpack16
    #image: chiefmate/tensorspot_ps:v9-no-log # yeonhooy/tensorspot_ps:v9 # hwan94/tensorspot-scheduler:0.0.26
