apiVersion: kubeflow.org/v1
kind: "TFJob"
metadata:
  name: id12-squad-gpt2l-sync-batch16
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    CHIEF:
      replicas: 1
      template:
        metadata:
          annotations:
            "tensorspot/num_chief": "1"
            "tensorspot/num_worker": "4"
            "tensorspot/net_request": "5917"
            "tensorspot/gpu_limit": "1.0"
            "tensorspot/gpu_request": "1.0"
            "tensorspot/gpu_mem": "85899345920"
            "tensorspot/placement_policy": "spot"
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            env:
            - name: ROOT_DATA_DIR
              value: "/data"
            args:
              - JOB=`python /workspace/job_name.py`;
                mkdir -p /result/id12_squad_gpt2l_sync_batch16;
                echo "id12_squad_gpt2l_sync_batch16" > /workspace/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`; echo "$STARTTIME" > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_start_time.txt;
                top -d 0.1 -b | grep python > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_cpu.txt & python /workspace/nlp_jobs/gpt2l_dist_squad.py --batch_size 4 --num_batches 253;
                ENDTIME=`date "+%H:%M:%S.%N"`; echo "$ENDTIME" > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_end_time.txt
            ports:
              - containerPort: 2222
                name: tfjob-port
            image: potato4332/nlp-image:0.0.1
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /data
              name: tfjob-dataset
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: tfjob-dataset
            persistentVolumeClaim:
              claimName: tfjob-nfs-dataset-storage-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker
          schedulerName: tensorspot-scheduler
    WORKER:
      replicas: 3
      template:
        metadata:
          annotations:
            "tensorspot/num_chief": "1"
            "tensorspot/num_worker": "4"
            "tensorspot/net_request": "5917"
            "tensorspot/gpu_limit": "1.0"
            "tensorspot/gpu_request": "1.0"
            "tensorspot/gpu_mem": "85899345920"
            "tensorspot/placement_policy": "spot"
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            env:
            - name: ROOT_DATA_DIR
              value: "/data"
            args:
              - JOB=`python /workspace/job_name.py`;
                mkdir -p /result/id12_squad_gpt2l_sync_batch16;
                echo "id12_squad_gpt2l_sync_batch16" > /workspace/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`; echo "$STARTTIME" > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_start_time.txt;
                top -d 0.1 -b | grep python > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_cpu.txt & python /workspace/nlp_jobs/gpt2l_dist_squad.py --batch_size 4 --num_batches 253;
                ENDTIME=`date "+%H:%M:%S.%N"`; echo "$ENDTIME" > /result/id12_squad_gpt2l_sync_batch16/id12_squad_gpt2l_sync_batch16_${JOB}_end_time.txt
            ports:
              - containerPort: 2222
                name: tfjob-port
            image: potato4332/nlp-image:0.0.1
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /data
              name: tfjob-dataset
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: tfjob-dataset
            persistentVolumeClaim:
              claimName: tfjob-nfs-dataset-storage-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
              twonode: worker
          schedulerName: tensorspot-scheduler