apiVersion: kubeflow.org/v1
kind: "TFJob"
metadata:
  name: id7-squad-gpt2m-sync-batch32
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    CHIEF:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            env:
            - name: ROOT_DATA_DIR
              value: "/data"
            args:
              - |
                JOB=`python /workspace/job_name.py`;
                mkdir -p /result/id7_squad_gpt2m_sync_batch32;
                echo "id7_squad_gpt2m_sync_batch32" > /workspace/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`; echo "$STARTTIME" > /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB}_start_time.txt;
                top -d 0.1 -b | grep python > /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB}_cpu.txt & nsys profile --duration=1200 -o /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB} --force-overwrite true python /workspace/nlp_jobs/gpt2m_dist_squad.py --batch_size 4 --num_batches 10;
            ports:
              - containerPort: 2222
                name: tfjob-port
            image: potato4332/nlp-image:fixed-tfds
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /data
              name: tfjob-dataset
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: tfjob-dataset
            persistentVolumeClaim:
              claimName: tfjob-nfs-dataset-storage-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker
    WORKER:
      replicas: 7
      template:
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            env:
            - name: ROOT_DATA_DIR
              value: "/data"
            args:
              - |
                JOB=`python /workspace/job_name.py`;
                mkdir -p /result/id7_squad_gpt2m_sync_batch32;
                echo "id7_squad_gpt2m_sync_batch32" > /workspace/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`; echo "$STARTTIME" > /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB}_start_time.txt;
                top -d 0.1 -b | grep python > /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB}_cpu.txt & nsys profile --duration=1200 -o /result/id7_squad_gpt2m_sync_batch32/id7_squad_gpt2m_sync_batch32_${JOB} --force-overwrite true python /workspace/nlp_jobs/gpt2m_dist_squad.py --batch_size 4 --num_batches 10;
            ports:
              - containerPort: 2222
                name: tfjob-port
            image: potato4332/nlp-image:fixed-tfds
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /data
              name: tfjob-dataset
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: tfjob-dataset
            persistentVolumeClaim:
              claimName: tfjob-nfs-dataset-storage-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
              twonode: worker
